# Change these first
owner: biosimulations # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository

sites:
  - name: Biosimulations API
    url: https://api.biosimulations.org
  - name: runBioSimulations API
    url: https://run.biosimulations.org
  - name: BioSimulators API
    url: https://api.biosimulators.org
  - name: Ingress Loadbalancer
    check: "tcp-ping"
    url: 34.123.157.17
    port: 80
  - name: Storage Buckets
    check: "tcp-ping"
    url: 155.37.254.142
    port: 80
  - name: Backend
    check: "tcp-ping"
    url: biosim-submit-ext.cam.uchc.edu
    port: 22
customStatusWebsitePackage: "@biosimulations/status-page"
status-website:
  themeUrl: https://status.biosimulations.org/biosimulations-theme.css
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.biosimulations.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/images/biosimulations-logo/logo-github.png
  name: BioSimulations
  introTitle: "Status of BioSimulations Service"
  introMessage: This is an automated monitoring page for BioSimulations services that can automatically create issues and send alerts. The site is built using  [upptime](https://github.com/upptime/upptime), a open source app.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/biosimulations/status-monitor
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
