# Change these first
owner: biosimulations # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - bilalshaikh42
  - jonrkarr
sites:
  - name: Biosimulations API
    url: https://api.biosimulations.org/health/status
  - name: BioSimulators API
    url: https://api.biosimulators.org/health
  - name: Combine API
    url: https://combine.api.biosimulations.org/health
  - name: Ingress Loadbalancer
    check: "tcp-ping"
    url: 34.123.157.17
    port: 80
  - name: Storage Buckets
    url: https://files.biosimulations.org/s3/helloWorld.txt
  - name: Backend
    check: "tcp-ping"
    url: biosim-submit-ext.cam.uchc.edu
    port: 22
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.biosimulations.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/images/biosimulations-logo/logo.svg
  name: "BioSimulations Status"
  introTitle: "BioSimulations/BioSimulators status monitor"
  introMessage: This page summarizes the status of BioSimulations' and BioSimulators' services.
  navbar:
    - title: View Status
      href: /
    - title: Edit Site
      href: https://github.com/biosimulations/status-monitor
  # themeUrl: https://status.biosimulations.org/biosimulations-theme.css
  css: |
    :root {
      --body-background-color: #ffffff;
      --body-text-color: rgba(0, 0, 0, 0.8);
      --card-background-color: #f7f7f7;
      --nav-background-color: #2196f3;
      --nav-border-bottom-color: #ffffff;
      --nav-current-border-bottom-color: #ffffff;
      --card-border-color: rgba(0,0,0,.12);
      --down-border-left-color: #f44336;
      --down-background-color: #ffd0d2;
      --degraded-border-left-color: #ff9800;
      --up-border-left-color: #38cc00;
      --tag-color: #ffffff;
      --tag-up-background-color: #38cc00;
      --tag-down-background-color: #f44336;
      --tag-degraded-background-color: #ff9800;
      --change-background-color: #ff9800;
      --error-button-border-color: #1a46ad;
      --error-button-background-color: #3867d6;
      --error-button-color: #ffffff;
      --submit-button-border-color: #1a46ad;
      --submit-button-background-color: #3867d6;
      --submit-button-color: #ffffff;
      --graph-opacity: 1;
      --graph-filter: hue-rotate(-64deg);
    }

    body {
      font-family: Raleway, Roboto, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif !important;
    }

    @media (min-width: 400px) {
      body {
        font-size: 14px !important;
      }
    }

    nav {
      color: #ffffff;
      font-weight: bold !important;
    }

    nav .container ul li a {
      padding: 1.5rem 1rem !important;
    }

    .container {
      max-width: 1000px !important;
    }
  links:
    - rel: stylesheet
      href: https://fonts.googleapis.com/css?family=Raleway
  favicon: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/icons/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/icons/favicon.svg
  metaTags:
    - name: "description"
      content: "Status monitor for BioSimulations and BioSimulators"
    - name: "keywords"
      content: "BioSimulations, BioSimulators, status, up, down, degraded"
    - name: "language"
      content: "EN"
    - name: "copyright"
      content: "Center for Reproducible Biomedical Modeling"
    - name: "author"
      content: "Center for Reproducible Biomedical Modeling, info@biosimulations.org"
    - name: "reply-to"
      content: "Center for Reproducible Biomedical Modeling, info@biosimulations.org"
    - name: "url"
      content: "https://status.biosimulations.org"
    - name: "identifier-URL"
      content: "https://status.biosimulations.org"
    - name: "application-name"
      content: "BioSimulations/BioSimulators status monitor"
    - name: "theme-color"
      content: "#2196f3"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
