# Change these first
owner: biosimulations # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - bilalshaikh42
sites:
  - name: Biosimulations API
    url: https://api.biosimulations.org
  - name: runBioSimulations API
    url: https://run.api.biosimulations.org
  - name: BioSimulators API
    url: https://api.biosimulators.org
  - name: Combine API
    url: https://combine.api.biosimulations.org/kisao/get-similar-algorithms?algorithms=KISAO_0000019
  - name: Ingress Loadbalancer
    check: "tcp-ping"
    url: 34.123.157.17
    port: 80
  - name: Storage Buckets
    url: https://files.biosimulations.org/s3/helloWorld.txt
  - name: Backend
    check: "tcp-ping"
    url: biosim-submit-ext.cam.uchc.edu
    port: 22
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.biosimulations.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/images/biosimulations-logo/logo.svg
  name: ""
  introTitle: "BioSimulations/BioSimulators status monitor"
  introMessage: This page summarizes the status of BioSimulations' and BioSimulators' services.
  navbar:
    - title: Status
      href: /
    - title: BioSimulations
      href: https://biosimulations.org
    - title: runBioSimulations
      href: https://run.biosimulations.org
    - title: BioSimulators
      href: https://biosimulators.org
  themeUrl: https://raw.githubusercontent.com/biosimulations/status-monitor/master/assets/biosimulations-theme.css
  css: |
    body {
      font-family: Raleway, Roboto, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif !important;
    }

    @media (min-width: 400px) {
      body {
        font-size: 14px !important;
      }
    }

    nav {
      color: #ffffff;
      font-weight: bold !important;
    }

    nav .container ul li a {
      padding: 1.5rem 1rem !important;
    }

    .container {
      max-width: 1000px !important;
    }
  links:
    - rel: stylesheet
      href: https://fonts.googleapis.com/css?family=Raleway
  favicon: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/icons/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/icons/favicon.svg
  metaTags:
    - name: "description"
      content: "Status monitor for BioSimulations and BioSimulators"
    - name: "keywords"
      content: "BioSimulations, BioSimulators, status, up, down, degraded"
    - name: "language"
      content: "EN"
    - name: "copyright"
      content: "Center for Reproducible Biomedical Modeling"
    - name: "author"
      content: "Center for Reproducible Biomedical Modeling, info@biosimulations.org"
    - name: "reply-to"
      content: "Center for Reproducible Biomedical Modeling, info@biosimulations.org"
    - name: "url"
      content: "https://status.biosimulations.org"
    - name: "identifier-URL"
      content: "https://status.biosimulations.org"
    - name: "application-name"
      content: "BioSimulations/BioSimulators status monitor"
    - name: "theme-color"
      content: "#2196f3"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
