# Change these first
owner: biosimulations # Your GitHub organization or username, where this repository lives
repo: status-monitor # The name of this repository

sites:
  - name: Biosimulations API 
    url: https://api.biosimulations.org
  - name: runBioSimulations API
    url: https://run.biosimulations.org
  - name: BioSimulators API
    url: https://api.biosimulators.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.biosimulations.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/biosimulations/Biosimulations/dev/libs/shared/assets/src/assets/images/biosimulations-logo/logo-github.png
  name: BioSimulations
  introTitle: "Status of BioSimulations Service"
  introMessage: This is an automated monitoring page for BioSimulations services that can automatically create issues and send alerts. The site is built using  [upptime](https://github.com/upptime/upptime), a open source app.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/biosimulations/biosimulations

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
